from get_catalog import get_catalog

catalog = get_catalog()

from pyiceberg.schema import Schema
from pyiceberg.types import NestedField, StringType, DoubleType, DateType, BooleanType

company_schema = Schema(
    NestedField(1, "CompanyName", StringType(), required=True),
    NestedField(2, "CIK", StringType(), required=False),
    NestedField(3, "ISIN", StringType(), required=False),
	NestedField(4, "Ticker", StringType(), required=False),
	NestedField(5, "CUSIP", StringType(), required=False),
	NestedField(6, "Description", StringType(), required=False),
	NestedField(7, "Exchange", StringType(), required=False),
	NestedField(8, "ExchangeShortName", StringType(), required=False),
	NestedField(9, "Sector", StringType(), required=False),
	NestedField(10, "Country", StringType(), required=False),
	NestedField(11, "Currency", StringType(), required=False),
	NestedField(12, "City", StringType(), required=False),
    NestedField(13, "State", StringType(), required=False),
	NestedField(14, "Address", StringType(), required=False),
	NestedField(15, "Employees", StringType(), required=False),
	NestedField(16, "CEO", StringType(), required=False),
	NestedField(17, "Website", StringType(), required=False),
	NestedField(18, "ZipCode", StringType(), required=False),
	NestedField(19, "ADR", BooleanType(), required=False),
	NestedField(20, "isFund", BooleanType(), required=False),
	NestedField(21, "isETF", BooleanType(), required=False),
	NestedField(22, "AverageVolume", DoubleType(), required=False),
	NestedField(23, "Beta", DoubleType(), required=False),
	NestedField(24, "Discounted_Cash_Flow", DoubleType(), required=False),
	NestedField(25, "Discounted_Cash_Flow_Diff", DoubleType(), required=False),
	NestedField(26, "IPO_Date", DateType(), required=False),
	NestedField(27, "Industry", StringType(), required=False),
	NestedField(28, "Sector", StringType(), required=False),
	NestedField(29, "AsOfDate", DateType(), required=False),
)

ratio_schema = Schema(
			NestedField(1, "AsOfDate", DoubleType(), required=True),
			NestedField(2, "Asset_Turnover", DoubleType(), required=False),
			NestedField(3, "Capex_Per_Share", DoubleType(), required=False),
			NestedField(4, "Capex_To_Coverage_Ratio", DoubleType(), required=False),
			NestedField(5, "Capex_To_Operating_CashFlow_PCT", DoubleType(), required=False),
			NestedField(6, "Capex_To_Revenue_PCT", DoubleType(), required=False),
			NestedField(7, "Cash_Conversion_Cycle", DoubleType(), required=False),
			NestedField(8, "Cash_Per_Share", DoubleType(), required=False),
			NestedField(9, "Curren_Ratio", DoubleType(), required=False),
			NestedField(10, "Days_Of_Investory_OnHand", DoubleType(), required=False),
			NestedField(11, "Debt_To_Assets_PCT", DoubleType(), required=False),
			NestedField(12,"Debt_To_Equity_PCT", DoubleType(), required=False),
			NestedField(13,"Debt_To_Market_Cap_PCT", DoubleType(), required=False),
			NestedField(14,"Dividend_Per_Share", DoubleType(), required=False),
			NestedField(15,"Dividend_Yield_PCT", DoubleType(), required=False),
			NestedField(16,"EBIT_Per_Revenue", DoubleType(), required=False),
			NestedField(17,"Effective_Tax_Rate_PCT", DoubleType(), required=False),
			NestedField(18,"Enterprise_Value_Multiple", DoubleType(), required=False),
			NestedField(19,"Free_Cash_Flow_Per_Share", DoubleType(), required=False),
			NestedField(20,"Free_Cash_Flow_Yield_PCT", DoubleType(), required=False),
			NestedField(21,"Intangibles_To_TotalAssets", DoubleType(), required=False),
			NestedField(22,"Interest_Coverage", DoubleType(), required=False),
			NestedField(23,"Long_Term_Debt_To_Capitalization", DoubleType(), required=False),
			NestedField(24,"Net_Current_Assets", DoubleType(), required=False),
			NestedField(25,"Net_Debt_To_EBITDA", DoubleType(), required=False),
			NestedField(26,"Net_Income_Per_Share", DoubleType(), required=False),
			NestedField(27,"Net_Profit_Margin_PCT", DoubleType(), required=False),
			NestedField(28,"Operating_CashFlow_To_Sales_Ratio", DoubleType(), required=False),
			NestedField(29,"Operating_Cash_Flow_Per_Share", DoubleType(), required=False),
			NestedField(30,"Operating_Cycle", DoubleType(), required=False),
			NestedField(31,"Operating_Profit_Margin", DoubleType(), required=False),
			NestedField(32,"Payables_Turnover", DoubleType(), required=False),
			NestedField(33,"Pre_Tax_Profit_Margin_PCT", DoubleType(), required=False),
			NestedField(34,"Price_To_Book,Price_To_Earnings", DoubleType(), required=False),
			NestedField(35,"Price_To_Fair_Value", DoubleType(), required=False),
			NestedField(36,"Price_To_Sales_Ratio", DoubleType(), required=False),
			NestedField(37,"Quick_Ratio", DoubleType(), required=False),
			NestedField(38,"Receivables_Turnover", DoubleType(), required=False),
			NestedField(39,"Return_On_Capital_Employed_PCT", DoubleType(), required=False),
			NestedField(40,"Return_On_Equity_PCT", DoubleType(), required=False),
			NestedField(41,"Return_On_Invested_Capital_PCT", DoubleType(), required=False),
			NestedField(42,"Revenue_Per_Share", DoubleType(), required=False),
			NestedField(43,"Shareholders_Equity_Per_Share", DoubleType(), required=False),
			NestedField(44,"Short_Term_Coverage_Ratios", DoubleType(), required=False),
			NestedField(45,"Stock_Compensation_To_Revenue", DoubleType(), required=False),
			NestedField(46,"Tangible_Asset_Value", DoubleType(), required=False),
			NestedField(47,"Tangible_Book_Value_Per_Share", DoubleType(), required=False),
			NestedField(48,"Ticker", StringType(), required=False),
			NestedField(49,"Total_Debt_To_Capitalization_PCT", DoubleType(), required=False),
			NestedField(50,"Working_Capital_Local_Currency", DoubleType(), required=False),
)

for new_schema in [company_schema, ratio_schema]:
    catalog.create_schema(f"docs.{new_schema}", schema=new_schema)