from pyiceberg.schema import Schema
from pyiceberg.types import NestedField, StringType, DoubleType, DateType, BooleanType, IntegerType, TimestampType


company_schema = Schema(
	fields=(NestedField(field_id=1, name="AsOfDate", field_type=TimestampType(), required=True),
			NestedField(field_id=2, name="Ticker", field_type=StringType(), required=True),
	        NestedField(field_id=3, name="CompanyName", field_type=StringType(), required=False),
		    NestedField(field_id=4, name="CIK", field_type=StringType(), required=False),
		    NestedField(field_id=5, name="ISIN", field_type=StringType(), required=False),
			NestedField(field_id=6, name="CUSIP", field_type=StringType(), required=False),
			NestedField(field_id=7, name="Description", field_type=StringType(), required=False),
			NestedField(field_id=8, name="Exchange", field_type=StringType(), required=False),
			NestedField(field_id=9, name="ExchangeShortName", field_type=StringType(), required=False),
			NestedField(field_id=10, name="Sector", field_type=StringType(), required=False),
			NestedField(field_id=11, name="Country", field_type=StringType(), required=False),
			NestedField(field_id=12, name="Currency", field_type=StringType(), required=False),
			NestedField(field_id=13, name="City", field_type=StringType(), required=False),
		    NestedField(field_id=14, name="State", field_type=StringType(), required=False),
			NestedField(field_id=15, name="Address", field_type=StringType(), required=False),
			NestedField(field_id=16, name="Employees", field_type=StringType(), required=False),
			NestedField(field_id=17, name="CEO", field_type=StringType(), required=False),
			NestedField(field_id=18, name="Website", field_type=StringType(), required=False),
			NestedField(field_id=19, name="ZipCode", field_type=StringType(), required=False),
			NestedField(field_id=20, name="ADR", field_type=BooleanType(), required=False),
			NestedField(field_id=21, name="isFund", field_type=BooleanType(), required=False),
			NestedField(field_id=22, name="isETF", field_type=BooleanType(), required=False),
			NestedField(field_id=23, name="AverageVolume", field_type=DoubleType(), required=False),
			NestedField(field_id=24, name="Beta", field_type=DoubleType(), required=False),
			NestedField(field_id=25, name="Discounted_Cash_Flow", field_type=DoubleType(), required=False),
			NestedField(field_id=26, name="Discounted_Cash_Flow_Diff", field_type=DoubleType(), required=False),
			NestedField(field_id=27, name="IPO_Date", field_type=DateType(), required=False),
			NestedField(field_id=28, name="Industry", field_type=StringType(), required=False),

))

ratio_schema_ttm = Schema(
	fields=(NestedField(1, "AsOfDate", TimestampType(), required=True),
			NestedField(2,"Ticker", StringType(), required=True),
			NestedField(3, "Asset_Turnover", DoubleType(), required=False),
			NestedField(4, "Capex_Per_Share", DoubleType(), required=False),
			NestedField(5, "Capex_To_Coverage_Ratio", DoubleType(), required=False),
			NestedField(6, "Capex_To_Operating_CashFlow_PCT", DoubleType(), required=False),
			NestedField(7, "Capex_To_Revenue_PCT", DoubleType(), required=False),
			NestedField(8, "Cash_Conversion_Cycle", DoubleType(), required=False),
			NestedField(9, "Cash_Per_Share", DoubleType(), required=False),
			NestedField(10, "Current_Ratio", DoubleType(), required=False),
			NestedField(11, "Days_Of_Inventory_OnHand", DoubleType(), required=False),
			NestedField(12, "Debt_To_Assets_PCT", DoubleType(), required=False),
			NestedField(13, "Debt_To_Equity_PCT", DoubleType(), required=False),
			NestedField(14, "Debt_To_Market_Cap_PCT", DoubleType(), required=False),
			NestedField(15, "Dividend_Per_Share", DoubleType(), required=False),
			NestedField(16, "Dividend_Yield_PCT", DoubleType(), required=False),
			NestedField(17, "EBIT_Per_Revenue", DoubleType(), required=False),
			NestedField(18, "Effective_Tax_Rate_PCT", DoubleType(), required=False),
			NestedField(19, "Enterprise_Value_Multiple", DoubleType(), required=False),
			NestedField(20, "Free_Cash_Flow_Per_Share", DoubleType(), required=False),
			NestedField(21, "Free_Cash_Flow_Yield_PCT", DoubleType(), required=False),
	        NestedField(22, "Gross_Profit_Margin", DoubleType(), required=False),
	        NestedField(23, "Gross_Profit_Growth_PCT", DoubleType(), required=False),
			NestedField(24, "Intangibles_To_TotalAssets", DoubleType(), required=False),
			NestedField(25, "Interest_Coverage", DoubleType(), required=False),
			NestedField(26, "Long_Term_Debt_To_Capitalization", DoubleType(), required=False),
			NestedField(27, "Net_Current_Assets", DoubleType(), required=False),
			NestedField(28, "Net_Debt_To_EBITDA", DoubleType(), required=False),
			NestedField(29, "Net_Income_Per_Share", DoubleType(), required=False),
			NestedField(30, "Net_Profit_Margin_PCT", DoubleType(), required=False),
			NestedField(31, "Operating_CashFlow_To_Sales_Ratio", DoubleType(), required=False),
			NestedField(32, "Operating_Cash_Flow_Per_Share", DoubleType(), required=False),
			NestedField(33, "Operating_Cycle", DoubleType(), required=False),
			NestedField(34, "Operating_Profit_Margin", DoubleType(), required=False),
			NestedField(35, "Payables_Turnover", DoubleType(), required=False),
			NestedField(36, "Pre_Tax_Profit_Margin_PCT", DoubleType(), required=False),
			NestedField(37, "Price_To_Book", DoubleType(), required=False),
	        NestedField(38, "Price_To_Earnings", DoubleType(), required=False),
	        NestedField(39, "Price_To_Fair_Value", DoubleType(), required=False),
	        NestedField(40, "Price_To_Sales_Ratio", DoubleType(), required=False),
	        NestedField(41, "Quick_Ratio", DoubleType(), required=False),
	        NestedField(42, "R_And_D_ToRevenue", DoubleType(), required=False),
	        NestedField(43, "Receivables_Turnover", DoubleType(), required=False),
	        NestedField(44, "Return_On_Capital_Employed_PCT", DoubleType(), required=False),
	        NestedField(45, "Return_On_Equity_PCT", DoubleType(), required=False),
	        NestedField(46, "Return_On_Invested_Capital_PCT", DoubleType(), required=False),
	        NestedField(47, "Revenue_Per_Share", DoubleType(), required=False),
	        NestedField(48, "Shareholders_Equity_Per_Share", DoubleType(), required=False),
	        NestedField(49, "Stock_Compensation_To_Revenue", DoubleType(), required=False),
	        NestedField(50, "Tangible_Asset_Value", DoubleType(), required=False),
			NestedField(51, "Tangible_Book_Value_Per_Share", DoubleType(), required=False),
			NestedField(52,"Total_Debt_To_Capitalization_PCT", DoubleType(), required=False),
			NestedField(53,"Working_Capital_Local_Currency", DoubleType(), required=False),
))

forecast_schema = Schema(
	fields=(NestedField(1, "AsOfDate", TimestampType(), required=True),
			NestedField(2, "Ticker", StringType(), required=True),
			NestedField(3, "CalendarYear", IntegerType(), required=True),
			NestedField(4, "EstimateDate", DateType(), required=False),
			NestedField(5, "Debt_Growth_PCT", DoubleType(), required=False),
			NestedField(6, "Dividend_Per_Share_Growth", DoubleType(), required=False),
	        NestedField(7, "Dividend_Yield_PCT", DoubleType(), required=False),
			NestedField(8, "EBITDA_Growth_PCT", DoubleType(), required=False),
	        NestedField(9, "EBIT_Growth_PCT", DoubleType(), required=False),
			NestedField(10, "EPS_Diluted_Growth_PCT", DoubleType(), required=False),
	        NestedField(11, "EPS_Growth_PCT", DoubleType(), required=False),
	        NestedField(12, "Cash_Conversion_Cycle", DoubleType(), required=False),
	        NestedField(13, "Cash_Per_Share", DoubleType(), required=False),
	        NestedField(14, "Current_Ratio", DoubleType(), required=False),
	        NestedField(15, "Debt_To_Equity", DoubleType(), required=False),
	        NestedField(16, "Debt_To_Asset", DoubleType(), required=False),
	        NestedField(17, "Debt_To_EBITDA", DoubleType(), required=False),
	        NestedField(18, "Debt_To_EBIT", DoubleType(), required=False),
	        NestedField(19, "Debt_To_Operating_CashFlow", DoubleType(), required=False),
	        NestedField(20, "Debt_To_Revenue", DoubleType(), required=False),
	        NestedField(21, "Debt_To_Shareholders_Equity", DoubleType(), required=False),
	        NestedField(22, "Equity_To_Asset", DoubleType(), required=False),
			NestedField(23, "Five_Year_Dividend_Per_Share_Growth", DoubleType(), required=False),
			NestedField(24, "Five_Year_Net_Income_Growth_Per_Share", DoubleType(), required=False),
			NestedField(25, "Five_Year_Operating_CashFlow_Growth_Per_Share", DoubleType(), required=False),
			NestedField(26, "Five_Year_Revenue_Growth_Per_Share", DoubleType(), required=False),
			NestedField(27, "Five_Year_Shareholders_Equity_Growth_Per_Share", DoubleType(), required=False),
			NestedField(28, "Free_CashFlow_Growth_PCT", DoubleType(), required=False),
	        NestedField(29, "Free_CashFlow_Per_Share", DoubleType(), required=False),
			NestedField(30, "Gross_Profit_Growth_PCT", DoubleType(), required=False),
	        NestedField(31, "Gross_Profit_Margin", DoubleType(), required=False),
			NestedField(32, "Inventory_Growth_PCT", DoubleType(), required=False),
			NestedField(33, "Net_Income_Growth_PCT", DoubleType(), required=False),
	        NestedField(34, "Net_Income_Per_Share", DoubleType(), required=False),
			NestedField(35, "Operating_CashFlow_Growth_PCT", DoubleType(), required=False),
	        NestedField(36, "Operating_CashFlow_Per_Share", DoubleType(), required=False),
			NestedField(37, "Operating_Income_Growth_PCT", DoubleType(), required=False),
			NestedField(38, "Revenue_Growth_PCT", DoubleType(), required=False),
			NestedField(39, "RD_Expense_Growth_PCT", DoubleType(), required=False),
			NestedField(40, "Period", StringType(), required=False),
			NestedField(41, "Receivables_Growth_PCT", DoubleType(), required=False),
	        NestedField(42, "Receivables_Turnover", DoubleType(), required=False),
			NestedField(43, "SGA_Expense_Growth_PCT", DoubleType(), required=False),
			NestedField(44, "Three_Year_Shareholders_Equity_Growth_Per_Share", DoubleType(), required=False),
            NestedField(45, "Three_Year_Revenue_Growth_Per_Share", DoubleType(), required=False),
			NestedField(46, "Three_Year_Operating_CashFlow_Growth_Per_Share", DoubleType(), required=False),
			NestedField(47, "Three_Year_Net_Income_Growth_Per_Share", DoubleType(), required=False ),
			NestedField(48, "Three_Year_Dividend_Per_Share_Growth", DoubleType(), required=False),
			NestedField(49, "Ten_Year_Shareholders_Equity_Growth_Per_Share", DoubleType(), required=False),
			NestedField(50, "Ten_Year_Revenue_Growth_Per_Share", DoubleType(), required=False),
			NestedField(51, "Ten_Year_Operating_CashFlow_Growth_Per_Share", DoubleType(), required=False),
			NestedField(52, "Ten_Year_Net_Income_Growth_Per_Share", DoubleType(), required=False),
			NestedField(53, "Ten_Year_Dividend_Per_Share_Growth", DoubleType(), required=False)
))